### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by jamiter** [Voog/wysihtml#105]
This is a great library with even a package.json. So a simple question: Why isn't this published to npm?

Thanks for all the great work!

**Comment by dustinhayes** [comment]
Is this feature still being considered?

**Comment by pulges** [comment]
Published.
https://www.npmjs.com/package/wysihtml

**Comment by EgorIgorevich** [comment]
Great News!!!

**Comment by santiagotactivos** [comment]
Hi! sorry, but 
```
var wysihtml =  require('wysihtml');
```
is not working for me after installing through npm returns a object of the shape:

```
function (grunt) {

  "use strict";

  // List required source files that will be built into wysihtml5x.js
  var base = [
    "src/polyfills.js",
    "src/wysihtml5.js",
    "node_modules/rangy/lib/rangy-core.js",
    "node_modules/rangy/lib/rangy-selectionsaverestore.js",
    "lib/base/base.js",
    "src/browser.js",
....

```

**Comment by nicolasiensen** [comment]
Same as @santiagotactivos, how are we supposed to instantiate wysihtml package?

**Comment by royaldark** [comment]
You guys are seeing that issue because for some reason package.json has `"main": "Gruntfile.js"`. For Wysihtml to work well with Browserify and other packagers, package.json will need to also have `"browser": "dist/wysihtml.js"`.

**Comment by nicolasiensen** [comment]
Thanks a lot @royaldark, but now the error I'm getting is the following:
```
ERROR in ./~/wysihtml/dist/wysihtml.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./rangy-core in /Users/nicolasiensen/Projects/hub-client/node_modules/wysihtml/dist
 @ ./~/wysihtml/dist/wysihtml.js 4323:8-41
```

**Comment by unr** [comment]
If only this was resolved. 

Still unable to use npm to install wysihtml.
