### ISSUE TITLE
Automatically Resize Text Editor

### ISSUE THREAD

**Issue by kurtfunai** [Voog/wysihtml#106]
First off, thank you for keeping this project alive and active!

Just curious, is there a setting that would allow the editor to automatically resize?
Previously I was using the xing/wysihtml5 library, and I was able to get my text area to resize using https://github.com/smidwap/wysihtml5_size_matters 
Demo available here: http://smidwap.github.io/wysihtml5_size_matters/demo/index.html

Unfortunately this approach doesn't seem to work for this project any longer. Is there a better way to accomplish this?

**Comment by ChristofferJoergensen** [comment]
@kurtfunai could you elaborate on how you got [wysihtml5_size_matters](https://github.com/smidwap/wysihtml5_size_matters) to work properly with [wysihtml](https://github.com/Voog/wysihtml)?

My setup looks like the one described in the [Getting started](https://github.com/Voog/wysihtml/wiki/Getting-Started) WIKI entry.

My HTML looks like this:

    <form>
        <div id="wysihtml-toolbar" style="display: none;">
            ...
        </div>
        <textarea id="wysihtml-textarea"</textarea>
    </form>
    <div id="wysihtml-div"></div>

My Javascript initiation looks like this:

    $("#wysihtml-textarea").val("Lorem ipsum");
    var editor = new wysihtml5.Editor("wysihtml-textarea", {
        toolbar:      "wysihtml-toolbar",
        parserRules:  wysihtml5ParserRules
    });

So far so good. But as for the `wysihtml5_size_matters` method I have unsuccessfully tried to apply it to both the `$(editor.composer.iframe)` object:

    editor.on('load', function() {
        $(editor.composer.iframe).wysihtml5_size_matters();
    });

and to the `$("#wysihtml-div")` div as per your suggestion:

    editor.on('load', function() {
        $("#wysihtml-div").wysihtml5_size_matters();
    });

In both cases no errors are raised, but no functionality triggered either. Could you descibe how you managed to make it work?

**Comment by kurtfunai** [comment]
Hey @ChristofferJoergensen,

You do not need to include wysihtml5_size_matters. This version of wysihtml has the autosizing functionality built in. 

I also notice that you are using a text area. Unfortunately the auto-sizing functionality did not work properly for me when using a `<textarea>`, but it worked correctly when switching it to a `<div>`. I also believe using divs make this library much cleaner, so it is a win-win.

Side note: I'm not sure if this was a typo on your behalf, but you're missing a closing `>` on your text area.
```<textarea id="wysihtml-textarea"</textarea>```


Try changing your code to something like the following:
```html
<form>
    <div id="wysihtml-toolbar" style="display: none;">
        ...
    </div>
    <div id="wysihtml-textarea"></div>
</form>
<!-- you no longer need the <div id="wysihtml-div"></div> -->
```
```javascript
$scope.editor = new hwWysihtml5.Editor("wysihtml-textarea", {
      toolbar:      "wysihtml-toolbar", 
      parserRules:  wysihtml5ParserRule
    });

// you dont need any of the on load events here, because you no longer need wysihtml5_size_matters().
```

**Comment by ChristofferJoergensen** [comment]
Great, thanks for the thorough explanation :-)
