### ISSUE TITLE
How to "close" the editor?

### ISSUE THREAD

**Issue by alessandrofrancesconi** [Voog/wysihtml#109]
I'm using this nice tool to make a classic `<div>` editable for a moment, then I want to make it switch back to its normal form.
Is there a function for this? I tried with `disable()` but it just makes the editor... uneditable.

**Comment by yourcelf** [comment]
I've run into this problem when showing the editor in a modal and needing to destroy/rebuild on show/hide.  I'm using an iframe/textarea, and these are the steps I've had to take:

 - remove the iframe
 - replace the toolbar to unbind events (using something like jQuery.clone and jQuery.replaceWith works well to rebuild the toolbar without stale bound events).
 - replace the textarea to unbind events (same clone trick, though you have to manually copy the textarea's value also)

A convenient destroy() or unbind() would be really nice to save that hassle.

**Comment by mschering** [comment]
+1

**Comment by oscarotero** [comment]
+1

**Comment by thec0keman** [comment]
I've been using a very similar solution to @yourcelf , however after upgrading to 0.5-beta12 Chrome is giving this exception:
```
Cannot read property 'rangeCount' of undefined
```
(This is not fatal).

All of that to say: +1 to getting an internal method that properly can teardown the app.

**Comment by mschering** [comment]
Anything new on this? I'm using it in an angularjs project and I'm afraid it will leak memory if not properly destroyed in each view.

**Comment by tiff** [comment]
With pull request #212 the exception doesn't appear anymore. @thec0keman

**Comment by hmillet** [comment]
Useful method !! Thanks

**Comment by filipe-nunes** [comment]
I think this issue is still not completely resolved... even with editor.destroy() and editor = null, my toolbar keeps the old events...
