### ISSUE TITLE
Toggle bold 3 times doesn't work

### ISSUE THREAD

**Issue by iamdanfox** [Voog/wysihtml#120]
Repro (in Chrome 38.0.2125.104 on a mac)

1. http://wysihtml.com/
2. Highlight some text, e.g. 'typing'
3. Click the bold icon in the top left three times

Expected:
The word 'typing' becomes bold, reverts to normal, then becomes bold again.

Actual:
The word 'typing' becomes bold, reverts to normal, but isn't bold again. (NB. the bold icon does end up emphasised)

![screen shot 2014-12-18 at 17 49 40](https://cloud.githubusercontent.com/assets/3473798/5493021/a553b038-86de-11e4-8c09-2b0bfee7741b.png)

**Comment by rryter** [comment]
@pulges any plans to resolve this?

**Comment by atipugin** [comment]
+1

**Comment by pulges** [comment]
Definitely, but it needs complete rewrite of html-applier and format-inline functionality. Currently i'm gathering ideas of how all this inline formatting and format removing should work universally (including styles). It needs a good spec to reflect user expectations on formatting so html markup would not dictate user behaviour but the other way around.
