### ISSUE TITLE
Using wysihtml with require.js

### ISSUE THREAD

**Issue by lovesh** [Voog/wysihtml#133]
I tried using wysihtml with requirejs. First it gave an error about missing `rangy`. So i looked at this issue https://github.com/Voog/wysihtml/issues/92 and made the suggested changes. Now the editor loads. But still it gives error when i try to paste an image in the editor. The error i get while pasting image is 
```
Uncaught Error: wysihtml5.Sandbox: Uncaught NotFoundError: Failed to execute 'setStartBefore' on 'Range': The node provided is null.    wysihtml5x_toolbar.js:7159
wysihtml5.dom.Sandbox.Base.extend._onLoadIframe.iframeWindow.onerror
Uncaught NotFoundError: Failed to execute 'setStartBefore' on 'Range': The node provided is null.       wysihtml5x_toolbar.js:2400
api.createCoreModule.createBeforeAfterNodeSetter    wysihtml5x_toolbar.js:1626
api.createCoreModule.util.extend.insertNode         wysihtml5x_toolbar.js:9483 wysihtml5.Selection.Base.extend.insertNode     wysihtml5x_toolbar.js:9466 wysihtml5.Selection.Base.extend.insertHTML   wysihtml5x_toolbar.js:13801 wysihtml5.Editor.wysihtml5.lang.Dispatcher.extend._cleanAndPaste  wysihtml5x_toolbar.js:13777 (anonymous function)        wysihtml5x_toolbar.js:4859
wysihtml5.lang.Dispatcher.Base.extend.fire   wysihtml5x_toolbar.js:13179
handlePaste wysihtml5x_toolbar.js:13179
```

I dont encounter any of these errors when i paste images in the editor in `advanced.html` at https://github.com/Voog/wysihtml/tree/master/examples.

What is the procedure to use `wysihtml` with require.js?

**Comment by veacks** [comment]
+1 Same problem with Browserify maybe we need to create a fork to be compilent with CommonJs/RequireJS ?

**Comment by atzoya** [comment]
I've had the same troubles and lost about a day while implementing the editor with require.js .
What worked for me in the end is this:

1. Inside the bootstrap3.wysihtml5.js file there are included rangy and rangy-selectionsaverestore, but they are also imported via require as modules in the same file. They need to be commented out from this file, and their paths need to be defined in the require setup.

2. Changing of names for some of the require modules so they can work togeateher

**Comment by pulges** [comment]
The new version 0.6.0-beta has removed the bundled rangy UMD wrappers now. Any other blocking problems when bundling or can the issue be closed?
