### ISSUE TITLE
Dialogues do not update attributes when focus changes in editor

### ISSUE THREAD

**Issue by stevethomas** [Voog/wysihtml#134]
If I have 2 or more links or images in the editor and click on one, the dialog is shown with the expected attributes; but if I click on a different element the attributes are still showing the initially selected element.

I don't think this is expected behaviour, I think it should switch context to whatever element is in focus in the editor. The only way to update the dialog is to cancel / ok the first one and click on the intended one. 

Is there a way to refresh a dialog when another element of the same type is selected?

**Comment by usmanity** [comment]
Hey @pulges @Rob-pw, could you guide me through a potential solution? I am happy to make a pull request.

**Comment by Rob-pw** [comment]
This issue should have been resolved in my PR, mainly commit 8e8f623afd5f5abd33548cc83627d2f1c3aef4cb from that set. If you could get latest and test that this is the case, I would really appreciate that!

**Comment by usmanity** [comment]
@Rob-pw thanks, how often do you tag new releases? It looks like that commit missed the lastest release version.

**Comment by pulges** [comment]
Will probably release next beta this week.
The release is basically @Rob-pw commit with some refactoring, commenting and fixes/additions trying to make it a bit more future proof for the directions we are hoping to go.

**Comment by pulges** [comment]
Fixed in https://github.com/Voog/wysihtml/pull/184
