### ISSUE TITLE
I keep getting broken html links, no matter what case

### ISSUE THREAD

**Issue by ayyobro** [Voog/wysihtml#135]
Links keep on breaking when inserted into the iframe, no matter what I try

Test_text = http://www.laravel.io is a great place to learn

Copy and paste output: http://www.laravel.io">http://www.laravel.io is a great place to learn

Using the link builder button output: http://laravel.io">laravel.io is a great place to learn

Typing it by hand output: http://laravel.io">http://laravel.io is a great place to learn

complete html of problem area: \
```
<p><a href="&lt;a target=" _blank"="">http://laravel.io</a>"&gt;<a target="_blank" href="http://laravel.io">http://laravel.io</a>&nbsp;is a great place to learn</p>
```

**Comment by ayyobro** [comment]
Fixed it myself

**Comment by kasoban** [comment]
Care to explain? Was this a problem with wysihtml or your project setup? If the cause was in wysihtml, can you share your fix for others?
