### ISSUE TITLE
Correct use for Bower main

### ISSUE THREAD

**Issue by redgluten** [Voog/wysihtml#136]
From the [Bower doc](https://github.com/bower/bower.json-spec): the purpose of `main` is to describe “The primary acting files necessary to use your package”. 

I’m using main-bower-files to concatenate and minify my js assets, the current references to     "dist/wysihtml5x.min.js" and "dist/wysihtml5x-toolbar.min.js" doesn’t allow this usage.

**Comment by pulges** [comment]
f04e11e20e782928115e66cb6ce9d25d7872e4e1
