### ISSUE TITLE
IE pasting problems

### ISSUE THREAD

**Issue by nicoabie** [Voog/wysihtml#140]
When using the editor in "div" mode and pasting any text in browsers IE8, IE9, IE10 and IE11
the page scrolls and the paste event is prevented, (just getting beforepaste but not paste)

With the debugger I found out the problem is thing line
```
cleanerDiv.focus();
``` 
In the following function 
```
wysihtml5.dom.getPastedHtmlWithDiv
```

Commenting it out solves the problem

**Comment by pulges** [comment]
The focus is in a pollyfill for browsers that do not support catching pasted content first for cleanup, before inserting to content. Cured the focus scroll with moving the helper paste catcher into viewport.
