### ISSUE TITLE
ParserRules - Change ImageTagAttribut

### ISSUE THREAD

**Issue by doktorsuarez** [Voog/wysihtml#148]
is there a way to define a parser rule that does something like this with the image tag:

img src="images/test.jpg"

replace with:

img src="temp/images/test.jpg"

if not, would be thankful for an idea of a workaround.
Thx

**Comment by pulges** [comment]
I just added an enhancement that You can pass a function to check_attributes method in parser rules
in parser rules for image tag you would have to add something like this:

    check_attributes: {
        src: function(val) {
            if (val.indexOf('temp/') !== 0) {
                return "temp/" + val;
            } else {
                return val;
            }
        }
    }
