### ISSUE TITLE
formatBlock crashes when removing previous state

### ISSUE THREAD

**Issue by ungue** [Voog/wysihtml#153]
I have integrated this editor inside Ember.js framework and all goes well until y click a format command twice. This executes the next snippet:

    // Remove state if toggle set and state on and selection is collapsed
      if (options && options.toggle) {
        state = this.state(composer, command, options);
        if (state) {
          bookmark = rangy.saveSelection(composer.win);
          for (var j in state) {
            removeOptionsFromElement(state[j], options, composer);
          }
        }
      }

And the issue comes here

     for (var j in state) {
        removeOptionsFromElement(state[j], options, composer);
     }

`state` is an array with several methods and properties, for example it contains `_super`, so iterating in this way would produce :

![image](https://cloud.githubusercontent.com/assets/882427/6482249/557b5428-c264-11e4-8bb0-ba7c1e89c3a8.png)

We should avoid this kind of constructions when playing with arrays. I think you should use something like:

    for(var i = 0; i < state.length; i += 1)

when iterating through arrays to avoid this kind of issues.

This is the final step to get a full Ember.js integration, please dont forget me :smile:

**Comment by pulges** [comment]
Sorry, I completely forgot to correct this after testing various methods.

**Comment by ungue** [comment]
Thanks a lot man
