### ISSUE TITLE
How to init wysihtml for a "simple line of text"?

### ISSUE THREAD

**Issue by alessandrofrancesconi** [Voog/wysihtml#156]
Great, GREAT library!
Anyway, I would like to make an editable `<div>`, in a way that it will act like a classic `<input type="text">`.
In particular, it must not parse any HTML character and line break. So, for example, if the user hits the spacebar it will write a simple " " character, not a "`&nbsp;`", and when the user hits the return button, the editor simply ignores it instead of inserting a `<br>`.

I tried with this with no luck:

    wysihtml5.Editor(titleElem, {
        name: "editor-title",
        parserRules: {},
        autoLink: false,
        style: false,
    });

**Comment by pulges** [comment]
Currently there is no way to do that. Parser rules are applied on some occasions like paste, getValue, etc.. and they are actually not intended to apply on every single edit that happens. I think wysihtml would be probably too mush of code to implement for this functionality too.

Can tell what are you trying to do and what would using contenteditable give more than just input?

**Comment by alessandrofrancesconi** [comment]
Understood. I'm currently preparing a platform to write some articles, so there is a big editable area for the contents and a small one for the title. Both of them are managed by two instances of wysihtml, but since the title shouldn't be HTML-ized, I'll probably switch to a simpler <input>.
