### ISSUE TITLE
Editor formatting issues

### ISSUE THREAD

**Issue by M-Porter** [Voog/wysihtml#158]
Hey there,

There is an issue with formatting when using `<p>` instead of `<div>` dom elements.

When using `<p>`, if you create a new line then delete that line, the text after the inserted line becomes formatted as header text. This side effect doesn't occur when using `<div>`.

[Here's a gif of what I mean.](http://i.imgur.com/0EMJI2s.gifv)

Try it out for yourself at http://jsbin.com/rodoru.

**Comment by pulges** [comment]
Currently editor does not detect and therefore allow initiating it on elements that can not contain other block level elements. Paragraphs and headings are one of these elements that allow only phrasing content. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p
If initiated on P for isnstance editor must make sure that no divs/paragrapsh/headings etc are inserted. Currently no such mode is possible.

Nevertheless the error presists even in div elements and I will keep the issue open and try to fix. 

Create editor on div containing a paragraph. Make paragraph have font-size: 1.5em; and do not define fontsize in pixels on any parent including body. The default native erroneous behavior of webkit based browsers should add span with the same font-size: 1.5em; around the live after caret when deleting.
