### ISSUE TITLE
Removing formatting from element after moving cursor then coming back - broken

### ISSUE THREAD

**Issue by nonpc** [Voog/wysihtml#166]
Hello,
It's pretty basic - moving a cursor after applying a formatting, then going back to remove the formatting does not work and throws errors.

Here's a simple .gif to show: 
![wysihtml](https://cloud.githubusercontent.com/assets/2235868/7086606/a2fc461e-df8b-11e4-9ef5-2f8e20d72f7b.gif)

It does seem to be a pretty major issue since it breaks one of the most basic functionalities.

**Comment by pulges** [comment]
Short testing showed this error with newer versions of firefox. I'm actually already rewriting the whole inline formatting logic from scratch as it has become erroneous, bloated and on the limit of being un-fixable. Unfortunately I can not give an estimate though when it will be ready and tested.
