### ISSUE TITLE
Why the dialog opened automaticly when focus on a link?

### ISSUE THREAD

**Issue by luozhihua** [Voog/wysihtml#167]

**Comment by pulges** [comment]
Currently the optional toolbar and dialogue logic dictates that the dialogue of a state is always is opened when the state becomes active. Writing custom toolbar logic should not be too difficult. https://github.com/Voog/wysihtml/blob/master/examples/wotoolbar.html

Also You can make a pull request changing the toolbar logic that I will be happy to review. As I am using wysihtml with my own custom toolbar logic, improving and fixing the toolbar component is not directly in my to-do lists currently.
