### ISSUE TITLE
Toggling states still problematic

### ISSUE THREAD

**Issue by kpost** [Voog/wysihtml#182]
When I'm trying to toggle a state of selected text (let's say, bold) more than once, it seems earlier reported problems are still there. After toggling bold to normal, empty bold nodes appear on each side of the selected text. This was referenced in #120 and #85. On Chrome, various toggles also puts the html char ```&#65279;``` in front of the selected text. On Safari everything seems to work.

I'm on OS X 10.10.3.

![image](http://g.recordit.co/q0p8Cmwcve.gif)

**Comment by pulges** [comment]
The editor on wysihtml.com site is currently not up to date as the latest release is still in beta. Will try to finish it and update soon.

**Comment by furedal** [comment]
Is this issue resolved in the latest release? I am using version 0.6.0.beta1 and are having exactly this issue in chrome Version 54.0.2840.71 (64-bit) on Mac.

It seems to be working on your preview website.
