### ISSUE TITLE
best way to set font family

### ISSUE THREAD

**Issue by cristianbell** [Voog/wysihtml#187]
Hi, 

One issue that I have is setting font-family for a text selection. (from a drop-down with different font families). 
As I was using v0.4.17, I did the following: 
- created a CSS class for each font family in the list;
- upon clicking on the desired font family the setFontFamily function was called
- it got the font family name, created the CSS class for it and also the Regex name
- then I used the following command to apply it: 
var success = crtEditor.composer.commands.exec("formatBlock", "span", className, classNameRegex);

it worked in 4.1.7, but it doesn't in the latest version - 5, beta10. 

Why is this suddenly not working anymore? (Pb because of the formatBlock update in 0.5.beta1). 
Which is the best way to set font families for a text selection? Why isn't this actually possible using formatInline (would make more sense to apply the font-family there).. 

Thanks!

**Comment by pulges** [comment]
The syntax of formatBlock and formatInline is changing in v5 (thus in beta) to give more options and better better configutarion. I'm still to document it when all options settle finally. Also when inserting inline elements like span it is better to use formatInline that follows inline tag rules. You have to change the command like this

var nodeOptions = {
    nodeName: "SPAN", // if omitted DIV is default
    className: "font-style-1",
    classRegExp: /font-style-[0-9a-z]+/g, // not needed if you do not have 
    toggle: true // if applying same option on already formated block removes(toggles) format or not (default is true for formatInline)
};
crtEditor.composer.commands.exec("formatInline", nodeOptions);

Currently to see more options and configurations you'll have to scan the tests written
https://github.com/Voog/wysihtml/blob/master/test/commands/formatInline_test.js

**Comment by cristianbell** [comment]
Hi and thanks! 
It now seems to be working, but there a couple of issues. 
The most importat one, would be the applying of multiple font families. If apply different font families over the same selection the result is not great: 
<span class="arial robobotblack impact segoeprint">some text</span>. 
I tried naming all the fonts using a scheme - ftfa[A-Z]{4} - and using this as a regex. My hope was that the WYSIWYG will only apply 1 font family and upon calling the formatInline it will replace the existing font family - if any - with the new one. 

But this does not happend. Is there any way to do this? And/or how can I read the currently applied font family?  

Thanks, 
Cristian
