### ISSUE TITLE
using formatInline to apply font families - not really working

### ISSUE THREAD

**Issue by cristianbell** [Voog/wysihtml#188]
Hi, 
following the resolution for #187 I use formatInline to apply font families to different selections of text. 

This works ok for a continuous editing, but not so great if you save the content to a database; 
- edit the content, the font family is applied, bold, italic, size, etc as well. 
- let's say the edited content is saved to the database.
- reload the page and fill the WYSIWYG <div> container with the content from the DB. 
- click on edit (initialize the WYSIWYG on the div and w/ a corresponding toolbar)
this is where the problem happens: the WYSIWYG removes all <span class="Roboto..."> tags, while not touching other <span > tags for Bold/Underline/Italic, font size, font color. 

I initialize it using the following:
	editors[selectedElement] = new wysihtml5.Editor('' + selectedElement, {
			toolbar: toolbarId,
			parserRules: wysihtml5ParserRules,
			cleanUp: true,
            		useLineBreaks:  false
});

I tried taking out cleanUp, it didn't change the behaviour. 

thanks!

**Comment by pulges** [comment]
If you are adding tags with custom classes or styles, you have to add them to parser rules too.
For classes you need to update the section classes

    "classes": {
        "wysiwyg-clear-both": 1,
        "wysiwyg-clear-left": 1
....

you can also use 

    "classes":  "any"

If using styles to add font-family you have to change the tag rules. for span:
    
    "span": {
        "keep_styles": {
            "fontFamily": 1
        }
    }

**Comment by cristianbell** [comment]
I am using the advanced_and_extended.js and there "classes" is already set to "any". 
I also added the "fontFamily": 1 line to "span", but nothing changed. Is there no better way of applying font families? 

Thanks!

**Comment by pulges** [comment]
Will look into it, there might be a bug.

**Comment by cristianbell** [comment]
Hi, 
I looked over the code a little more. 
Adding fontFamily: 1 doesn't make much sense, as I'm using classes to apply font-families not actual style="font-family" attributes. 

In order to fix the issue I had to modify the wysiwyg a little bit - at the level of node removal/unrap/rename. For example in \wysihtml\dist\wysihtml-toolbar.js on line 6896 I added another else if condition (afer unwrap and rename): 
        }else if (rule.remove_action === "leave_unchanged"){
          return true; 
and of course in the parser rules, under "span" I changed "remove_action":"unwrap" to "remove_action": "leave_unchanged". 

If you set "remove_action" to anything else than unwrap, rename you fall into the else condition, which just removes the node. 

Cheers, 
C

**Comment by cristianbell** [comment]
Hi, 

looked over the code a little bit more, and the issue seems to be in the function _handleElement(). 

after 
```javascript
if (rule.one_of_type && !_testTypes(oldNode, currentRules, rule.one_of_type, clearInternals)) {
      if (rule.remove_action) {
        if (rule.remove_action === "unwrap") {
...
```
I added a new condition: 
```javascript
       }else if (rule.remove_action === "leave_unchanged"){
          //do nothing
```
and of course in the parser rules I changed the remove_action for "spam" to
```javascript
"remove_action": "leave_unchanged",
```

All is good now, the span elements are no longer stripped of class at startup. 

Cheers, 
C

**Comment by pulges** [comment]
OK, problem is that advanced_and_extended.js uses one_of_type logic to check if span is valid. It has to match atleast one of the types given to pass cleanup. The types are defined in "type_definitions" section of rules. You should add your classes to "text_formatting_object" classes definition list.

The current reason for such handling in advanced_and_extended.js is that if we allow all classes then browsers tend to add a lot of garbage classes with spans to content. These classes are used internally by the browser and have nothing to do with actual user edits. In ideal world browsers should never use DOM manipulation tricks in contenteditable to store their data/state about elements, but its not ideal world.

**Comment by cristianbell** [comment]
thanks. This is a little cumbersome if you use dynamically generated classes for font-family :) 
I'll stick to my "branch" though, so far using the extra "leave_unchanged" value has worked well.

**Comment by Dayjo** [comment]
@cristianbell What's your solution to font family setting? I was looking to do font family classes, but I can't get it working nicely at all. Getting all sorts of odd toggling issues and not 'saving' properly.
