### ISSUE TITLE
changing/applying new font family using formatInline - does not remove old class, it just adds a new one

### ISSUE THREAD

**Issue by cristianbell** [Voog/wysihtml#189]
Hi, 
As per Pulges suggestion (thanks!) I am using formatInline to apply different font families over portions of selected text. 
In order to do this I created several classes, one for each family. 
If you only apply a font family class over a portion of text, it works great. If you try to apply different font families over the same selection the result is not great: 
< span class=" verdana impact roboto " >...

I tried naming all the fonts using a scheme - ftfa[A-Z]{4} - and using this as a regex. My hope was that the WYSIWYG will only apply 1 font family and upon calling the formatInline again it will replace the existing font family - if any - with the new one.

But this does not happend. The result is exactly as above but with other class names: 
< span class=" ftfaVDNA ftfaIMPA ftfaRBTO " >...

Is there any way to archive the behavior I expect? 
And/or how can I read the currently applied font family?

Thanks, 
Cristian

**Comment by nevf** [comment]
I'm having the same issue. I think the way to resolve is for the functions that call ```formatInline.exec()``` to call ```formatInline.remove()``` first. This may not be appropriate for all functions that use formatInline, but it is for font name, size, color, bgcolor etc.

I've been using the original xing version of wysihtml5 in my app [Clibu](http://www.clibu.com) and am in the process of switching to this version, so I am a bit new to it.

**Comment by nevf** [comment]
Also see my issue: https://github.com/Voog/wysihtml/issues/247
