### ISSUE TITLE
Where to store the Editor content?

### ISSUE THREAD

**Issue by steffimueller** [Voog/wysihtml#190]
I like your great work. Thanks for sharing. 

When I create a texturea: 

```
<form>
    <textarea id="wysihtml-textarea" placeholder="Enter your text ..." autofocus></textarea>
</form>
```

Where would you recommend to store the final content of the textarea after submitting the form? Would you store it in a mysql text field or as a html file?

**Comment by confile** [comment]
+1 @pulges great to get your idea on this too?

**Comment by pulges** [comment]
It is totally up to you and your backend code. Storing in database might give you more flexibility and better security management in the long run.
