### ISSUE TITLE
Extend Examples

### ISSUE THREAD

**Issue by confile** [Voog/wysihtml#191]
Could you please extend the examples with the editor presented here: http://wysihtml.com/

The toolbar is very nice. But the css in there only minified. 

Is there also an unminified version of this css available?

**Comment by pulges** [comment]
Probably will not have time to do it in the summer months. If you don't mind some digging then the whole unminified template code for VOOG cms of wysihtml.com website, including the editor, toolbar and icons, is here https://github.com/Voog/wysihtml-website for anyone to explore.

**Comment by confile** [comment]
Great thank you!

**Comment by confile** [comment]
@pulges Where do you get the svg icons of the toolbar from?

**Comment by confile** [comment]
I is really hard to extract the toolbar from all this code. Could you please specify which files do I need to make also the JavaScript working?
