### ISSUE TITLE
Server Side when HTML5 Parser is used

### ISSUE THREAD

**Issue by steffimueller** [Voog/wysihtml#192]
I use:

```
parserRules:  wysihtml5ParserRules
```

Tags are perfectly striped out. So why do I need Server Side Security, because when I submit the form there is not valid html anymore?

**Comment by pulges** [comment]
Everything in browser is in clients machine and under clients control. Defining parser rules is for normal user to have better and cleaner code (no tags he can not edit later). If the user is a hacker, any security measures targeted against him in front-end is a matter of one click fix for the hacker. Even further, hacker can ignore the  browser altogether and just post malicious data to your form url from command line if he wishes. Thus validity, sql injection etc tests have to be made server side that is under your control. I suggest just trying some front end hacking out yourself by right clicking in any webpage in Chrome browser and choosing inspector from context menu.
