### ISSUE TITLE
Security Issue when modifying DOM

### ISSUE THREAD

**Issue by confile** [Voog/wysihtml#193]
Here is a possible security issue. 

When you load a page which contains the editor and you insert the following line in the part where the toolbar is: 

```
<a data-wysihtml5-action="change_view">switch to html view</a>
```

Then an attacker can insert anything into the form.

**Comment by pulges** [comment]
I think fixing security issues on front end side, where attacker is the owner/viewer of the browser, is already a lost cause. All browsers provide such thing as console under right click, giving owner of the browser a convenient ui for any thinkable modification or running any script he wants. This level of security has to be provided server-side unfortunately.
