### ISSUE TITLE
Bind and unbind the toolbar at runtime

### ISSUE THREAD

**Issue by nicolasiensen** [Voog/wysihtml#196]
I'm implementing a page with many wysihtml instances and instead of creating one toolbar for each editor, I wanted to have just one toolbar to rule them all.

I was planning to implement it by creating the main toolbar and initializing every wysihtml instance with no toolbar in the configuration.

When any editor receives an on focus event, I would bind this editor to the main toolbar, and when it receives an on blur event, I would unbind this editor from the main toolbar. Does it make sense?

I didn't found a simple way to bind/unbind toolbars at runtime, how could I make it work? Thanks!

**Comment by pulges** [comment]
Unfortunately there is currently no methods to do that with default toolbar. Only way is to build your own custom toolbar currently. If you wish to do that you can look the custom toolbar example on building a custom toolbar:
https://github.com/Voog/wysihtml/blob/master/examples/wotoolbar.html#L241
