### ISSUE TITLE
justifyRight vs. alignRightStyle

### ISSUE THREAD

**Issue by confile** [Voog/wysihtml#198]
What is the difference between justifyRight and alignRightStyle?

**Comment by pulges** [comment]
the difference is that originally "justifyRight" added a class to block element. This had the limitation of having to have a list of classes with predefined styles in your sites template.
As we are using the editor for CMS purposes ourselves and we wanted to reduce the overhead that template writer has to know, we added commands that do the same things with style attribute directly to element (commands with Style suffix).
