### ISSUE TITLE
composerClassName not taken into account

### ISSUE THREAD

**Issue by boppy** [Voog/wysihtml#205]
The config option "composerClassName" is ignored. I cannot even find that string in wysihtml-toolbar.js and wysihtml.js (I really hope not to overlook something ^^).

I'll try to collect some more info and perhaps even a fix. But not before saturday.

**Comment by pulges** [comment]
All classes options are currently changed to classNames options
classNames.composer is what you should be changing now.

https://github.com/Voog/wysihtml/blob/master/src/editor.js#L74

The refactor is currently is currently half way done. The idea is to have all (even ithe inline, temprorary ones) classes brought out there, so namespace changing would become possible.

**Comment by pulges** [comment]
Updated specification:
https://github.com/Voog/wysihtml/wiki/Configuration
