### ISSUE TITLE
Editor looses cursor upon toolbar interaction

### ISSUE THREAD

**Issue by Isigiel** [Voog/wysihtml#209]
As you can experience for yourself here http://wysihtml.com/, every time a action on the toolbar is clicked, the cursor disappears. But you can still continue writing.
Is there a way to change that behaviour to the cursor still being displayed?

**Comment by ZeGregg** [comment]
+1

**Comment by pulges** [comment]
There is a way to change the behaviour: fixed it by updating the editor to latest version.

**Comment by ZeGregg** [comment]
I this supposed also to fix the issue that make loose text selection when clicking on a button that open a dropdown?

**Comment by pulges** [comment]
Is it loosing selection in some cases?

**Comment by ZeGregg** [comment]
In fact this is mostly highlight than selection. On http://voog.github.io/wysihtml/examples/advanced.html select a word then click color, you loose the selection highlight. Here is a [fiddle](https://jsfiddle.net/Greggg/63qsfdgb/1/) with dropdown. On hover it works fine but if you click to access dropdown selection is lost

**Comment by pulges** [comment]
Hmm, did not update the editor there. Will have to do that also then.

**Comment by ZeGregg** [comment]
And on [fiddle](https://jsfiddle.net/Greggg/63qsfdgb/1/) with dropdown. On hover it works fine but if you click to access dropdown selection is lost

**Comment by pulges** [comment]
The input must have focus or user can not insert. Multiple selections are not supported cross browser.

**Comment by ZeGregg** [comment]
Not sure to understand :( There is no Multiple selections! Is ther a way to prevent lose text selection when clicking on a dropdown trigger?

**Comment by pulges** [comment]
The selection is not lost. It is remembered and clicking ok or cancel restores it and inserts the format to the selection (in case of OK). What we can not do is diplay caret/selection in input at the same time as showing caret or selection in editable area.

**Comment by ZeGregg** [comment]
I fixed the issue on my by switching trigger from <a> to <button>
