### ISSUE TITLE
Bold, Italic, Underline creates <br>

### ISSUE THREAD

**Issue by Myridor** [Voog/wysihtml#214]
Everytime I click on Bold Italic or Underline it adds an < br>
to the end of my text.

So the html looks like this if I click on Bold and Italic:

< p>< b>< i>Some of my Text< /i>< /b>< /p>
< br>
< br>

**Comment by bzach** [comment]
I can confirm this in chrome.

When creating a new line blank line in the editor, the HTML is <p><br></p>

When clicking on Bold, the html becomes <p><b></b><br></p> with the <br> outside the <b> tags. When you start typing the html becomes <p><b>Some text</b><br></p> leaving an extra <br> tag in there.
