### ISSUE TITLE
Destroy editor and make new editor

### ISSUE THREAD

**Issue by Dannybevers** [Voog/wysihtml#215]
Hello,

I'm using this wysihtml plugin. I have a list of items and generate on the fly a wysihtml editor like this.
```
        PlaylistOverview.editor = new wysihtml5.Editor(PlaylistItemEdit.$currentElement.find('.playlist-item-editor textarea').get(0), {
            toolbar: 'toolbar',
            autoLink: false,
            parserRules:  wysihtml5ParserRules
        });
```

But when i open a new playlist item they gives an error.

```
Error in Rangy WrappedSelection module: getNativeSelection(): Parameter must be a Window object or DOM node
```

Is it possible to destroy the whole editor and make a new one without an error.

**Comment by pulges** [comment]
The command should be like this

     PlaylistOverview.editor.destroy();
     // if you need to remove the element or toolbar from DOM, do it aftewards
     // PlaylistItemEdit.$currentElement.find('.playlist-item-editor textarea').remove();
     // $('#toolbar').remove();

As the destroy command is implemented today, if it errors could you make a test case. Even better add a test to wysihtml tests showing it if possible.

**Comment by Dannybevers** [comment]
Thanks, is it possible to compile the plugin to /dist folder?
The compiled version in /dist folder didn't have the awesome destroy function.

**Comment by Dannybevers** [comment]
Fixed. Compiled by reading readme.
