### ISSUE TITLE
Placeholder styling

### ISSUE THREAD

**Issue by mark222** [Voog/wysihtml#227]
Requesting a means to style the placeholder. Usually a placeholder is light-gray as an indicator to the user that it is not actual text in the field. Currently one cannot distinguish the placeholder from real user-entered text.

**Comment by pulges** [comment]
When placeholder is present the editable area gets class wysihtml5-placeholder. It can be configured too: https://github.com/Voog/wysihtml/wiki/Configuration#classnames. Adding scss to styles using that class should achieve what you requested.

**Comment by mark222** [comment]
My bad, I looked exactly there but somehow missed the placeholder style. Thanks.

**Comment by mark222** [comment]
Still could not get this to work, finally discovered the documentation is wrong. The default class name for the placeholder is not "wysihtml5-placeholder", it is just "placeholder".
