### ISSUE TITLE
Directive for AngularJS created

### ISSUE THREAD

**Issue by fipartners** [Voog/wysihtml#237]
Hi,

I've made a directive in Angular JS to use wysihtml

If it helps, see : https://gist.github.com/fipartners/26da52f9394c6bdf7396

**Comment by feruzm** [comment]
it is helpful, @fipartners Do you have updated version which is compatible with latest version?

It did work, but when I click on toolbar button, it freezes or doesn't add newly typed characters.

I am testing it on mobile not on desktop, maybe mobile is not fully supported?

**Comment by fipartners** [comment]
I have it updated. Some bug remain like an event still sending signal when you look in the console
