### ISSUE TITLE
Add table class automatically

### ISSUE THREAD

**Issue by Oviglo** [Voog/wysihtml#241]
I want to add automatically a class in a table (<table class="table">), I try to change the parserRule file but it don't work:
<code>
"table": {
            "keep_styles": {
                "width": 1,
                "textAlign": 1,
                "float": 1
            },
            "check_attributes": {
                "id": "any"
            },
            "add_class": {
                "table": "table"
            }
        },
</code>

Can you help me ?

**Comment by pulges** [comment]
Will be available with next release (today). The class will be inserted when cleanup occurs (not at table insertion though currently). Cleanup can be triggered manually by editor.cleanUp()

**Comment by pulges** [comment]
and released

**Comment by Oviglo** [comment]
Thank you :)
