### ISSUE TITLE
ExecCommand problem

### ISSUE THREAD

**Issue by Oviglo** [Voog/wysihtml#242]
Hi,
I try to write my custom toolbar (I don't use the default toolbar) and I have a problem with somes commands:
<code>
    $('a[data-wysi-command="bold"]').click(function(){
        console.log(wysiEditor);
        wysiEditor.focus(false)
        wysiEditor.composer.commands.exec('bold');
    });
</code>

When I click on my button, the seletected text does'nt change.
Can you help me for this please ?
Thanks.

**Comment by pulges** [comment]
$('a[data-wysi-command="bold"]').click(function(event) {
       event.preventDefault();
       wysiEditor.composer.commands.exec('bold');
    });

Look here for longer example: https://github.com/Voog/wysihtml/blob/master/examples/wotoolbar.html#L357

**Comment by Oviglo** [comment]
I try your code but it don't works for me:
<code>

    $('a[data-wysi-command="bold"]').click(function(event){
        event.preventDefault();
        console.log('Bold command');
        composer.commands.exec('bold');
    });

    $('a[data-wysi-command="alignCenterStyle"]').click(function(event){
        event.preventDefault();
        console.log('Align center command');
        composer.commands.exec('alignCenterStyle');
    });</code>

It work with "alignCenterStyle" command.

**Comment by Oviglo** [comment]
Ok I found the bug, I forgot to write the code: 
<code>
// Prevent buttons from deselecting selected text before action is performed
    $(".editor-btn").mousedown(function(event){
      var b = composer.selection.getBookmark();
      event.preventDefault();
      
      // ie8 bug fix. mousedown does not prevent loosing focus
      setTimeout(function() {
        composer.selection.setBookmark(b);
      }, 0);
      
    });
</code>
