### ISSUE TITLE
Alignment commands

### ISSUE THREAD

**Issue by evanbennett** [Voog/wysihtml#245]
In the GitHub Wiki, on the Supported Commands page:
* 'justifyFull' is listed, but not described below
* 'alignCenterStyle', 'alignLeftStyle' and 'alignRightStyle' are not listed or described

On a slightly different note, should there be a 'alignFullStyle' command?

I could try to fix these if you want?

**Comment by pulges** [comment]
Currently there are a million commands that all directly map to formatBlock, making the code quite a bit bigger. I'm considering documenting the formatBlock better (with all the command examples) after i've finished improving it and provide the referring commands as an alternative backwards compatibility  package.

**Comment by evanbennett** [comment]
Sounds good. Thanks.

**Comment by nevf** [comment]
@pulges I've also just noticed the alignXYZStyle commands and that they are missing from the Wiki.

However I am having trouble getting justifyRight, Center etc. to work reliably both in my code and in the  examples. For example sometimes a justify command does nothing at all. Are you aware of any issues with justify?

**Comment by pulges** [comment]
Hi,

I’m currently improving the formatBlock command for reliability. If You could provide some description of how to reproduce the error (also browser and version), I’d be glad to look at. Maybe I can figure out and fix the problem.

Oliver Pulges

**Comment by nevf** [comment]
@pulges Sorry this was a problem with my code. I deleted the post, hoping it wouldn't be seen.
