### ISSUE TITLE
Setting a color, font name etc. keeps adding classes.

### ISSUE THREAD

**Issue by nevf** [Voog/wysihtml#247]
If you use the ```advanced.html``` example, add a word, select it, then click ```green``` and then ```blue``` you finish up with ````<span class="wysiwyg-color-green wysiwyg-color-blue">fred</span>````

Depending on the order of the rules in the css file the word will be either green or blue. IMO there should only be one class name set for a give type _(color, bgColor, fontName etc)_.

One way to resolve this is for the functions that call ```formatInline.exec()``` to call ```formatInline.remove()``` first. This may not be appropriate for all functions that use formatInline, but it is for font name, size, color, bgcolor etc.

I'd appreciate feedback from more experienced users as to whether there is a better way to resolve this.

I've been using the original xing version of wysihtml5 in my app [Clibu](http://www.clibu.com) and am in the process of switching to this version, so I am a bit new to it.

**Comment by pulges** [comment]
Tested, seems to be a bug in formatInline and using class regexp. Will look into it soon

**Comment by nevf** [comment]
Thanks. I expected the regexp with it's ```/g``` to remove all existing matches, but that isn't the case.
