### ISSUE TITLE
wysihtml5.toolbar.Toolbar is not a constructor

### ISSUE THREAD

**Issue by Globulopolis** [Voog/wysihtml#248]
Got this error when use editor with custom toolbar.
Error raised on
```javascript
this.toolbar = new wysihtml5.toolbar.Toolbar(this, this.config.toolbar, this.config.showToolbarAfterInit);
```

Any suggestion?

**Comment by nevf** [comment]
This seems strange. I'm creating a custom Toolbar in my app Clibu as per your code and it works perfectly. 

Stepping through it in the debugger may shed more light on the cause.

**Comment by Globulopolis** [comment]
Hmm...
Maybe it's was my mistake. Forgot to add toolbar script.
