### ISSUE TITLE
Editor ignore space 

### ISSUE THREAD

**Issue by altmann** [Voog/wysihtml#252]
The problem is that the editor ignore spaces. I have the latest version of wysihtml (0.5.2).

**Comment by pulges** [comment]
Would you give some further details: os, browsser, version, how you are initializing / using wysihtml etc, how specifically is it ignoring them.

**Comment by altmann** [comment]
Thanks for your fast response. Problem already solved. The problem was that the bootstrap carousel component catch the space keydown event and so all spaces were ignored in the editor.
