### ISSUE TITLE
dialog field input values randomly change

### ISSUE THREAD

**Issue by stevethomas** [Voog/wysihtml#257]
I'm trying to add a styling option to the create link dialog, which involves adding Bootstrap "btn btn-primary" classes.

On some occasions, this works just fine, but there appears to be a bug where the value attribute changes; sometimes it changes to blank, sometimes it inherits the values of other inputs in the dialog. 

For example the default radio input is randomly assigned value="btn btn-primary" after some links are inserted.

I believe I have narrowed the issue down to the use of radios instead of select elements, and the _interpolation function not correctly (re)assigning values. I suspect this has to do with the the duplicate input name required on radio groups but i'm not sufficiently skilled in javascript to be certain or to submit a fix.

```
    // allow some additional class names
    wysihtml5ParserRules.classes["btn"] = 1;
    wysihtml5ParserRules.classes["btn-primary"] = 1;

....

<!-- createLink dialog -->
    <div data-wysihtml5-dialog="createLink" class="well" style="display: none;">
        <div class="form-group">
            <label class="col-md-3 control-label">Link</label>

            <div class="col-md-9">
                <input data-wysihtml5-dialog-field="href" value="http://www.example.com" class="form-control">
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Button Style</label>

            <div class="col-md-9">
                <label class="radio-inline">
                    <input type="radio" name="btn-style" data-wysihtml5-dialog-field="class" value="">
                   Default
                </label>

                <label class="radio-inline">
                    <input type="radio" name="btn-style" data-wysihtml5-dialog-field="class" value="btn btn-primary">

                    <div class="btn btn-primary btn-xs">Primary Button</div>
                </label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <a data-wysihtml5-dialog-action="save" class="btn btn-success">OK</a>
                <a data-wysihtml5-dialog-action="cancel" class="btn btn-default">cancel</a>
            </div>
        </div>
    </div>
```

For those interested, the working equivalent is:

```
<select data-wysihtml5-dialog-field="class" class="form-control">
    <option value="">Default</option>
    <option value="btn btn-primary">Button Primary</option>
</select>
```

**Comment by pulges** [comment]
I think the current toolbar component does not have support for radio inputs. The problem is that radio inputs should be tested for being checked before getting the value like this:

    var value = document.querySelector('input[name="btn-style"]:checked').value;
