### ISSUE TITLE
What is the expected behavior of the 'plaintext' command?

### ISSUE THREAD

**Issue by cauburtin** [Voog/wysihtml#258]
Concerning the 'plaintext' button in the [advanced demo](http://voog.github.io/wysihtml/examples/advanced.html) with the attributes:

 `data-wysihtml5-command="formatBlock" data-wysihtml5-command-blank-value="true"`

What does it do exactly? Does it just erase a possible link https://github.com/Voog/wysihtml/blob/3fbfcb9da64bcbd34027a4b5f01841d2ae8765dc/src/toolbar/toolbar.js#L311?

I thought it would remove any wrapper of the text like `<b>text</b>` -> `text`  or   `<ul><li>text</li></ul>` -> `text`

**Comment by pulges** [comment]
Currently it only removes block format (headings, divs, paragraphs etc) from selection.

**Comment by cauburtin** [comment]
Ah ok, thanks Pulges, and thanks for that nice lib

As you're here :), don't you think it be interesting to make the 'plaintext' works for any HTML tag, block or inline. I see that you distinguish the formatBlock from the formatInline, but I'm not sure to understand why, is it because you want to make sure there won't be block inside inline elements? If yes, would it be possible to have a common command for them, but still enfore those rules (thus the plaintext would be easier to do)

**Comment by pulges** [comment]
Unifying the commands is not a simple problem to solve unfortunately. Especially concerning block-level elements that have many levels of content categories of their own, where some elements are not allowed into others and wrapping escapement must therefore be solved to comply with specifications. https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories
I'm not saying it is unsolvable. It is currently easier to solve both cases separately as final user interaction logic is not 100% settled.

Concerning the "plaintext" name in the examples for the command, I agree it is a bit misleading. Did not find a better name for "Remove text sectioning format". The remova all formatting command is already considered, but haven't had the time to implement it yet.

**Comment by cauburtin** [comment]
Thanks for your reply, 'plainttext' is ok actually, that was just me having hard times figuring out, something like remove block, or textnode could do too

I guess we could do a 'remove all formatting from selection' using textContent, I'll see if I can do it a bit later when I understand more

Sometimes I wish we could do a kind of `editor.composer.commands.exec("createHTML", '<div><span>Hello ${selection}</span></div>');`, it could throw an error if the given html is invalid, and it would try to make it work well with the selected text, how hard would it be?
