### ISSUE TITLE
How do you remove a span that was added for color/font?

### ISSUE THREAD

**Issue by cauburtin** [Voog/wysihtml#259]
https://jsfiddle.net/crl/foafka4a/48/ I'm trying to have a remove-color button, I've tried putting buttons with an empty attribute or no attribute without success.

What is the html or JS way to do this?

(docs https://github.com/Voog/wysihtml/wiki/Supported-Commands#forecolorstyle- )

**Comment by pulges** [comment]
Not sure the remove command is implemented into the  toolbar component. Currently you can do it using the remove command on editor

editor.composer.commands.remove('foreColorStyle');

https://jsfiddle.net/foafka4a/57/

**Comment by cauburtin** [comment]
thanks
