### ISSUE TITLE
isEmpty() in FF returns false when the value is empty

### ISSUE THREAD

**Issue by GGuru** [Voog/wysihtml#260]
Steps:

Without typing, add some markup into the editor using insertNode()
Then delete the markup
onblur isEmpty() returns false. It should return true.

**Comment by cauburtin** [comment]
try by setting the innerHTML maybe

**Comment by GGuru** [comment]
setting innerHTML = '' resets the selection api composer.selection.insertNode doesn't insert the node in the caret position.

**Comment by cauburtin** [comment]
what are you trying to do? could you do a quick fiddle on just the issue?

**Comment by GGuru** [comment]
Sorry. This is a wrong call. There is a space node hidden within the editor which is the reason for returning false. @cauburtin. Thanks for replying
