### ISSUE TITLE
setting a custom style attribute (not through existing commands)

### ISSUE THREAD

**Issue by cauburtin** [Voog/wysihtml#265]
I hoped I could do:

    composer.commands.exec("formatInline", "span", {styleProperty: 'fontFamily', styleValue: 'Lato'});

but unfortunately it's not that easy, http://jsfiddle.net/crl/foafka4a/72/

After checking https://github.com/Voog/wysihtml/blob/master/src/commands/formatInline.js#L139, I see that you can only set a class, why this limitation? It would be extremely pleasant to be able to manipulate styles directly

**Comment by pulges** [comment]
composer.commands.exec("formatInline", {nodeName: "span", styleProperty: 'fontFamily', styleValue: 'Lato'});

**Comment by cauburtin** [comment]
Great, thanks pulges, I was starting to make it using classes :)

other thing, why isn't toggle working? http://jsfiddle.net/crl/foafka4a/80/

I can still manage to remove it manually, but curious how this option work

**Comment by cauburtin** [comment]
I have this now http://jsfiddle.net/crl/foafka4a/86/

but I notice that you lose fonts initially like mentioned in https://github.com/Voog/wysihtml/issues/262, but also when going in the 'source' view

It's probably related, I guess the font-family should be made as a command for making this work well?

**Comment by pulges** [comment]
You need to configure the parser configuration object (wysihtml5ParserRules), so it will allow font-family style in span tags. You can look at https://github.com/Voog/wysihtml/blob/master/parser_rules/advanced_and_extended.js#L311 for reference.

**Comment by cauburtin** [comment]
ah, thanks :), I guessed it had to do with the parser

**Comment by pulges** [comment]
the rules are used to configure cleanup. It is mostly a whitelist of allowed tags and parameters and everything not in in will be removed.

**Comment by cauburtin** [comment]
makes sense, I saw it can remove also some <div> wrapping, thanks again pulges, 

(can you have a look at the alternative version,your answer is anyway helpful since the parser also removes classes if you don't allow them, but I'm afraid I'm not understanding well how the exec/state of a command work yet)

**Comment by pulges** [comment]
You should probably look at https://github.com/Voog/wysihtml/blob/master/examples/wotoolbar.html#L357
For an example of how to call commands on editor directly with javascript not built in toolbar (exec) 

In some cases selection can not be kept in editor on command inserting (for example user has to ender link address into an input). Then you have to save the selection and restore the selection later when user has inserted the value

saving selection to variable
    
    var bookmark = editor.composer.selection.getBookmark();

restoring selection:

  editor.composer.selection.setBookmark(bookmark);

**Comment by cauburtin** [comment]
Thanks I knew about the selection get and set, and about this example:)

The idea is to be able to add a font-family command, and maybe others, and be able to maintain a clean DOM (not an increasing number of `<span>` nesting), I'm hesitating between using style for everything, or classes for everything (both are possible, but that would be more consistent for my case to keep using one way or the other.

**Comment by cauburtin** [comment]
Thanks for your help @pulges, made this http://jsfiddle.net/crl/foafka4a/88/, I was surprised you don't need anymore to update active classes yourself
