### ISSUE TITLE
Cannot delete contenteditable=false elements in IE10

### ISSUE THREAD

**Issue by erikgui** [Voog/wysihtml#271]
Assuming I have the following HTML:
```html
<div contentEditable=true>
    <p>Hello <span contentEditable=false>cruel</span> world</p>
</div>
```
The `<span>` here cannot be deleted with backspace using wysihtml in IE10, but it works fine in Chrome, Safari, and Firefox. Is there a workaround for this issue using wysihtml?

**Comment by pulges** [comment]
Might not fix all cases, but should improve the un-editable detection in IE on delete. Problem was that IE does not respect whitespace when deleting correctly. By the spec it should collapse whitespace to 1 space and you should be able to delete that too with backspace. But in reality IE ignores the space and goes past it. Current delete detection could not see that delete coming.

Also added a way to track the un-editable that is being deleted, before delete (with event):

    document.body.addEventListener('wysihtml5:uneditable:delete', function(event) {
      console.log(event.target);
    });

**Comment by erikgui** [comment]
Thank you so much for your help, Oliver! Indeed, this does fixes most of my use cases!
