### ISSUE TITLE
Merge styles and classes

### ISSUE THREAD

**Issue by ZeGregg** [Voog/wysihtml#277]
Hi

Is there any way to merge inline style from 
`<span style="font-size: 10px"><span style="color: #CCC”>XOXO</span></span>` 
to 
`<span style="font-size: 10px; color: #CCC”>XOXO</span>`

and keeping the ability to remove one of theme without removing the entire` <span>`

Doing the same with classes would be nice and would make code lighter

Any help would be appreciated

**Comment by pulges** [comment]
In ideal world it should work if you add styles like this (not defining tag name):

    editor.composer.commands.exec("formatInline", {styleProperty: "color", styleValue: "blue", toggle: true});
    editor.composer.commands.exec("formatInline", {styleProperty: "fontSize", styleValue: "10px", toggle: true});

    // toggling off
    editor.composer.commands.exec("formatInline", {styleProperty: "fontSize", styleValue: "10px", toggle: true});

But in reality tag optimisation logic it is currently not complete and still working on it. So currently it still tends to add more spans or inline elements than needed.

**Comment by ZeGregg** [comment]
Thanks you @pulges Wait for next release ;-)
