### ISSUE TITLE
p tag by default

### ISSUE THREAD

**Issue by ZeGregg** [Voog/wysihtml#278]
If you empty editor then type content, there is no default tag applied to it. Maybe an option to force a p tag will be useful

Something like following should be a good practice

    <p>
	    <br>
    </p>

**Comment by pulges** [comment]
You probably just want to set this option to false:
https://github.com/Voog/wysihtml/wiki/Configuration#uselinebreaks

**Comment by ZeGregg** [comment]
:+1:
