### ISSUE TITLE
Table cells bgColor

### ISSUE THREAD

**Issue by ZeGregg** [Voog/wysihtml#279]
Hi. Any idea on how to apply bgColor on table cells?

**Comment by pulges** [comment]
editor.composer has an object tableSelection describing the table and cells selected if table cells are selected.
Currently we have used something like this (using custom toolbar):

    function addBgColor(color) {
        if(editor.composer.tableSelection) {
            editor.composer.tableSelection.cells.forEach(function(cell) {
                cell.style.backgroundColor = color;
            });
          });
        } else {
            editor.composer.commands.exec('bgColorStyle', color);
        }
    }

You will need to restore selection in editor before invoking this. You may also want to add some logic to do colour toggle if needed or use separate function with same logic to remove the colour.

**Comment by ZeGregg** [comment]
Thanks a lot @pulges for great help and support :+1:
