### ISSUE TITLE
Proposal on how users can consume wysihtml with a build system

### ISSUE THREAD

**Issue by hzoo** [Voog/wysihtml#290]
Wanted to know if any of the following could be done to improve how users can consume `wysihtml` (for users of build systems like webpack/browserify). I can try submitting a PR for these as well.

Related issue: #150. and maybe #133, #99, #92?
cc @inca since you mentioned converting to commonjs

1. Adopt ES6 modules (using something like babel) so people can just use that with their own build systems. Separately make a dist file that has no UMD innards but is wrapped in UMD.
2. Just make a dist file that has no UMD innards but is wrapped in UMD.
3. Make a dist file that has no UMD innards and exports a global.
4. Make a dist file that has no `rangy` built in and exports a global.

Thanks!

**Comment by Aintaer** [comment]
So currently there's several UMD shimmed modules in the distributable for wysihtml: `rangy` itself and some rangy extensions. This would not be a problem, except that in module loader environments, the UMD shim prefers module loaders and does not export the `rangy` global. This then leads to wysihtml not being able to find rangy.

Currently as we use `wysihtml` at Behance, we had to fork the repo, change the build script to not include rangy, then finally inject rangy into the wysihtml environment as a global using webpack. Not the most ideal solution, but it works.

**Comment by mikesherov** [comment]
So, as a middle ground solution, the easiest path forward with the most benefits for build systems like webpack would be to inline rangy but strip its UMD shim from the distributable.

**Comment by justcald** [comment]
Are there any updates on this..? Trying to use this with Webpack and having the exact issues that @Aintaer explained.

**Comment by pulges** [comment]
The new version 0.6.0 has removed the rangu UMD wrappers as proposed by @mikesherov. Can we close issue or is there more to it?

**Comment by mikesherov** [comment]
I think this is all.

**Comment by mikesherov** [comment]
Thanks @pulges !
