### ISSUE TITLE
IE8 is no longer supported?

### ISSUE THREAD

**Issue by BorelTung** [Voog/wysihtml#309]
In release info of version `0.5.2`, you said that
```
IE8 is no longer supported
```
But, in README, it is
```
The rich text editing interface is supported in IE8+, FF 29+, Safari 4+, Safari on iOS 5+, Opera 12+ and Chrome. 
```
What's the true browser support?

**Comment by pulges** [comment]
Thank you for pointing this out. I updated the readme.
IE8 support is currently in process of being removed, as it adds a lot of bulk weight and is also beginning prevent further improvements. In addition IE Edge is the new "black lamb in the herd", implementing a ton of non-standard behaviours to deal with :)
