### ISSUE TITLE
Remove Console.log

### ISSUE THREAD

**Issue by robertmain** [Voog/wysihtml#314]
Any chance you could remove console.log? Otherwise, things are going to break in IE9(console.log breaks IE9)

**Comment by pulges** [comment]
Hi, would yo mind referring to the problematic line where the console.log will break in IE9?
Currently I see only 2 places where this is used (one comes from rangy.js dependency) and both places seem to check if console.log is present before executing.

**Comment by robertmain** [comment]
Fair enough, sorry. Just figured saw a console.log appear in my console and
figured it wasn't being stripped. Should probably have read the code first
:p
