### ISSUE TITLE
Use HEX colors instead of RGB

### ISSUE THREAD

**Issue by alejandrogr** [Voog/wysihtml#318]
It is possible to use hex color codes instead of RGB in foreColorStyles command?

**Comment by pulges** [comment]
You should be able to insert colors with this command using the hex string too with the leading "#". The value should be converted automatically to the rgba string.

Lookat the end of this paragraph:
https://github.com/Voog/wysihtml/wiki/Supported-Commands#forecolorstyle-

Currently this command does not support inserting the color style attribute to code in hex format though, but You can copy the command source, rename the command and modify it to your liking.
https://github.com/Voog/wysihtml/blob/master/src/commands/foreColorStyle.js
Paste the source after you load wysihtml script and you have made a new custom command.

**Comment by alejandrogr** [comment]
Nice! thanks for the tip and links! will do a new command as i need the style to have the hex code instead the rgb.

Thanks!
