### ISSUE TITLE
Help - Adding Class using formatInline/formatBlock for Font Family

### ISSUE THREAD

**Issue by Dayjo** [Voog/wysihtml#323]
Hey guys, 

This isn't a bug, but need some advice, trying to create a simple 'addClass' command so that I can do font family. I've been trying to find some documentation somewhere on the best way to do font family but can't really find anything reliable, so I've come up with the following;

```js
wysihtml5.commands.addClass = {
            exec: function(composer, command, className) {
                var r = new RegExp("/" + className + "/", 'g')
                return wysihtml5.commands.formatBlock.exec(composer, 'formatBlock', {nodeName: 'span', className: className, classRegExp: r, toggle:true});
            },
            state: function(composer, command, className) {
                var r = new RegExp("/" + className + "/", 'g')
                return wysihtml5.commands.formatBlock.state(composer, 'formatBlock', {nodeName: 'span', className: className, classRegExp: r, toggle:true});
            }
        };
```

This manages to put the selection into a span with the class, but it keeps nesting spans with the classes i.e.

![](http://c.dayjo.me/383o1r022c2H/Image%202016-04-13%20at%2012.07.08%20pm.png)

This could just be related to @cristianbell problem here; https://github.com/Voog/wysihtml/issues/188

Any advice here would be really appreciated.

**Comment by Dayjo** [comment]
For anyone interested in how I solved this issue, I changed the command to formatInline like so;

```js
wysihtml5.commands.addClass = {
            exec: function(composer, command, className) {
                var r = /ff-[0-9a-z]+/g;
                return wysihtml5.commands.formatInline.exec(composer, 'formatInline', {nodeName: 'span', className: className, classRegExp: r, toggle:true});
            },
            state: function(composer, command, className) {
                var r = /ff-[0-9a-z]+/g;
                return wysihtml5.commands.formatInline.state(composer, 'formatInline', {nodeName: 'span', className: className, classRegExp: r, toggle:true});
            }
        };
```

I also added `"classes": "any"` to my wysihtml5ParserRules at the top level. ie.

```js
var wysihtml5ParserRules = {
    /**
     * CSS Class white-list
     * Following CSS classes won't be removed when parsed by the wysihtml5 HTML parser
     */
    "classes": "any",
```

I also added this (and some other properties) to the "span" tag definition, because the documentation isn't particularly clear exactly what these do. 

Personally I'm not clear on what is / isn't necessary here, I was not able to grasp it from the current docs, but perhaps someone could clarify.

```js
"span":
        {
            "one_of_type":
            {
                "text_formatting_object":1,
                "text_color_object":1
            },
            "keep_styles":
            {
                "color":1,
                "fontSize":1,
                "fontWeight":1,
                "fontStyle":1,
                "fontFamily":1
            },
            "remove_action":"unwrap",
            "classes": "any"
        },
```

**Comment by pulges** [comment]
@Dayjo  Trying to explain:

one_of_type is an option to pass as tests (defined above in file under "type_definitions"). If all of the type tests fail element gets removed or unwrapped (defined by "remove_action":"unwrap" here). (these not needed for the font class logic as they define currently only class or inline style color spans to be kept. If the color is also used a type for font names may be added)

keep styles defines what inline css styles to keep. If your editor does not use inline styles to add colors or other things this part can be discarded too

classes: "any" means all classes are allowed and kept. If you want to make the cleanup strict you can list allowed classes of your fonts and whatever is needed as an object

    "classes": {
                "ff-verdana": 1,
                "ff-arialt": 1
    };

currently classes test does not allow regexp for validity check unfortunately.

**Comment by Dayjo** [comment]
Thanks @pulges :) Yeah unfortunately I need to be able to add font classes on the fly so for now I'll stick to "any", shouldn't cause any issues I don't think. 

The classRegExp does seem to work nicely stripping out other fonts and replacing it with the one that I want.

**Comment by cristianbell** [comment]
Howdy! 
sorry for the late reply, I was away. 
My solution was: 
function _handleElement(oldNode, clearInternals), lines 6896 – 6897;
-	added code to handle class changes on HTML elements better. If there is a classRegExp defined, then all classes matching the regular expression will be removes when a new one is applied. The concept of the classRegExp was present in the wysihtml, but it was not fully implemented. 
function updateFormatOfElement (element, options), lines 12269 – 12281.

Also I had issues with the following scenario:
1. wysihtml box created; 
2. contents edited;
3. result is saved in the db;
4. page is refreshed, the box is created on load, content is added from the db; 
5. no matter how content is added upon first initialization when box becomes editable, the <span> and <div> tags were stripped of their classes.* 

my solution: 
file wysihtml-toolbar.js: 
-	added a HTML element rule - rule.remove_action = "leave_unchanged" to leave <span> and <div> tags unaffected when initializing the wysiwyg object for the first time. 

*: just a note here, the project could have an unlimited number of wysihtml boxes dynamically created upon pressing a button. I choose <div> as a container, as they also needed to be resizable, draggable (bound to a certain container, but also with safe and unsafe areas). 

hth

**Comment by Dayjo** [comment]
@cristianbell thanks! Yeah the bottom issue (5) I had, only way I could see to do it was to have "classes": "any" so the ability to use regex here would be grand.
