### ISSUE TITLE
Remove heading block by clicking the active button

### ISSUE THREAD

**Issue by Predjo** [Voog/wysihtml#337]
Clicking the heading button like the h1 or h2 should remove the heading block instead of the need for the plaintext button. It works like that for all the other buttons. 
For example here: http://voog.github.io/wysihtml/ there is no way to remove the heading without deleting it.

**Comment by pulges** [comment]
The logic is based on Microsoft Word. Idea is that block format is actually not add/remove but exclusive meaning `<p>` get replaced with `<h1>` as they can not contain each other by specification. Thus currently the default behaviour is a known decision reflecting the real behaviour that adding a tag will actually replace another one that is present. Inline tags (formatInline command) have another specification and their default logic ought to be toggle.

On the other hand the formatBlock command has the option toggle built in that can be set to true, thus the editor API has that support. For example toggling H1:

    wysihtml.commands.formatBlock.exec(composer, "formatBlock", {
        nodeName: "H1",
        toggle: true
     });

Problem is that the optional toolbar component has not support for passing additional parameters.

The easiest way to to configure for default toolbar is probably to create a custom wrapper command for formatBlock like this:

    wysihtml.commands.formatBlockToggle = (function() {
    
      var addToggleParamToOptions = function(options) {
        if (typeof options === 'string') {
          options = {
            nodeName: options,
            toggle: true
          };
        } else {
          options.toggle = true;
        }
        return options;
      };

      return {
        exec: function(composer, command, options) {
          options = addToggleParamToOptions(options;)
          return wysihtml.commands.formatBlock.exec(composer, "formatBlock", options);
        },
    
        state: function(composer, command, options) {
          options = addToggleParamToOptions(options;
          return wysihtml.commands.formatBlock.state(composer, "formatBlock", options);
        }
      };
    
    })();

In the toolbar you now should be able to just substitute the formatBlock command name with the new one:

    <a data-wysihtml-command="formatBlockToggle" data-wysihtml-command-value="h1">h1</a>

**Comment by Predjo** [comment]
That works! Thank you for a detailed explanation :)
