### ISSUE TITLE
Insert image with new version

### ISSUE THREAD

**Issue by Oviglo** [Voog/wysihtml#338]
Hello,
I download the new version in my project but I have an error when I insert image with this code:
`wysiEditor.composer.commands.exec("insertImage", { src: data['url'], alt: data['title'] });`
It create an 'img' markup but the src value is "[Object object]"

I don't find what do you change in the code.

Regards.

**Comment by pulges** [comment]
Do you include the full commands set package in your html (wysihtml.all-commands.js)? The basic wysihtml.js file only includes some core commands and the all-commands set includes all other commands. This allows to build your own bundle with only the commands you use.

**Comment by Oviglo** [comment]
Ah yes, I forgot to download this file.
Thanks alot for your fast response.
