### ISSUE TITLE
Using autofocus on a different field fails when wysihtml in loaded on the page

### ISSUE THREAD

**Issue by jwynveen** [Voog/wysihtml#340]
When there is another input on the page with the autofocus property, it loses focus immediately when the wysihtml script is loaded on the page. This only happens when the script is loaded at the bottom of the page. It works as expected when loaded in the head.

Reproduction: https://jsfiddle.net/jwynveen/5uundta8/

**Comment by Dayjo** [comment]
👍  - I wasn't sure this was just something I had messed up, but yeah, it's pretty annoying. When I go into a seperate contentEditable area 'too quickly' or into an input and start typing, shortly afterwards, the input loses focus.

**Comment by aaron** [comment]
The wysihtml toolbar also breaks autofocus on a textarea when the script is loaded before a textarea in Safari and Firefox (the autofocus works in Chrome in this case).

Example: https://jsfiddle.net/baldwina/uyaotypx/

As in the original report moving the script load after the textarea breaks the autofocus in Safari, Firefox, and Chrome.
