### ISSUE TITLE
When wysithml 0.6 stable is released

### ISSUE THREAD

**Issue by jack-vo** [Voog/wysihtml#355]
Thanks for the fantastic work, im wondering when we will roll out the stable version for 0.6 ?
Cheers

**Comment by pulges** [comment]
The beta in 0.6 does not mean it is unstable or not tested. We are actually using it in production in voog.com cms. I'm marking it as beta as i'm in process of trying to refactor the editor API to make it simpler and more transparent. Thus there will be many breaking change for the users (more work has to be done to migrate to the new version in users code). I'm trying to gather and do all needed the breaking changes now within this release to make the transition less painful. Can not give a deadline though, as I'm mostly doing it whenever i get some free time, and this is unpredictable.

If you are willing to implement the changes to your code side step-by-step in the near future, you can treat the 0.6 betas as stable and start using it now.

**Comment by jack-vo** [comment]
Thanks a lot for your reply @pulges 
We will implement 0.6 to our current app then.
Thanks for your great work
