### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by meowsus** [Voog/wysihtml#375]
153 open issues and 7 months without a commit. Two betas in the pipe for a v0.6.0 release, but no signs of movement on that release recently. Is this being abandoned at this point? Are you looking for a new maintainer?

**Comment by hennrunnel** [comment]
Hi @meowsus . In fact we are planning fixes and developments of the project just now here at [Voog](www.voog.com). Expect new commits in the near future.

**Comment by meowsus** [comment]
Glad to hear it! Thanks for the heads up!
