### ISSUE TITLE
IE11/Win8.1

### ISSUE THREAD

**Issue by andreaskian** [Voog/wysihtml#53]
IE11 creates paragraphs instead of &lt;br&gt; tags when hitting Enter

Tested on:
Windows 8.1
IE 11.0.9600.17107

**Comment by arcooverbeek** [comment]
+1

**Comment by pulges** [comment]
Fixed in https://github.com/Voog/wysihtml/commit/d1909f46e7a15686c0a8222b1a15935cf273a78b
