### ISSUE TITLE
Permit adding new methods to parse's attributeCheckMethods

### ISSUE THREAD

**Issue by cverond** [Voog/wysihtml#71]
The predefined set of methods available when using `parserRules` is usually sufficient, but sometimes you need to perform some work on attribute value. Unfortunately `attributeCheckMethods` is not exposed as a wysihtml5 attribute/configurable/extensible.
It would be nice if you could implement rules by your own by augmenting `parserRules` or by specifying functions directly in `check_attributes` as in:

`
a:      {
	check_attributes: {
		href:   function(av) { return [some elaboration on av]; }
	}
}
`

**Comment by pulges** [comment]
Added 79f13252a11154ea7b02248e000c7432bff26237
