### ISSUE TITLE
Preserve cursor position on editor.cleanUp()

### ISSUE THREAD

**Issue by tremby** [Voog/wysihtml#78]
It would be great to have cursor position preserved when running `editor.cleanUp()`.

Ideally if elements are removed the cursor would remain in the same position with respect to the text, rather than simply staying the same number of characters from the start of the field.

**Comment by starlocke** [comment]
I get the feeling that this no longer works, since the console logs this error when cleanUp() is invoked.

> Rangy warning: Module SaveRestore: Marker element has been removed. Cannot restore selection.
