### ISSUE TITLE
Issue with Rangy when loaded with requirejs

### ISSUE THREAD

**Issue by rayrigam** [Voog/wysihtml#92]
I just updated from version 0.4.9 to 0.4.15, and the code stoped working with the `ReferenceError: rangy is not defined`. It seems like there is an issue (https://github.com/timdown/rangy/issues/242) with the version of rangy used in wysihtml5 0.4.15. The issue shows up when using requirejs to load the script. Would it be possible to update to the latest Rangy code to see whether the error disappears?

**Comment by ldong** [comment]
second to what @rayrigam said, @alantsov 's fork fixed the `rangy` issue. Thanks.

**Comment by oscarotero** [comment]
The problem is wysihtml needs rangy variable as global even if rangy is loaded as AMD.
I've solved this problem in the configuration of requirejs:

```js
require.config({
	paths: {
		"wysihtml": "../bower_components/wysihtml/dist/wysihtml5x-toolbar",
		"rangy-core": "../bower_components/rangy/rangy-core"
	},
	map: {
		"wysihtml": {
			"rangy-core": "rangy-global"
		}
	},
	shim: {
		"wysihtml": {
			deps: ['rangy-core']
		}
	}
});
```

Then, we have to create the "rangy-global" module to load rangy and save it in global:

```js
define(['rangy-core'], function (rangy) {
	window.rangy = rangy;

	return rangy;
});
```

I hope when the 0.5.0 version is released, this patch is not needed.

**Comment by pulges** [comment]
The new version 0.6.0-beta has removed the bundled rangy UMD wrappers now. Any other blocking problems when bundling or can the issue be closed?
