### ISSUE TITLE
AMD vs globals factory incosistencies in the build

### ISSUE THREAD

**Issue by DimitarChristoff** [Voog/wysihtml#99]
When in a requirejs context, the build cannot be consumed.as rangy does not register itself globally (https://github.com/Edicy/wysihtml5/blob/master/dist/wysihtml5x.js#L78 has a todo) and it is being referenced from the outside without appropriate factory shimming:

`})(wysihtml5, rangy);`

https://github.com/Edicy/wysihtml5/blob/master/dist/wysihtml5x.js#L10267

the same applies to the global `wysihtml5`, which is an anti-pattern. probably grunt build task needs updating to add a closure around things 

additonally, the main amd module being returned is NOT the `wysihtml5` object as expected but the `rangy.createModule("SaveRestore", ["WrappedRange"], function(api, module) ..` instance, which makes it very impossible to use under AMD.  

returned obj looks like this:
```
{
  "version": "1.3alpha.20140804",
  "initialized": false,
  "supported": true,
  "util": {},
  "features": {},
  "modules": {
    "DomUtil": {
      "name": "DomUtil",
      "dependencies": [],
      "initialized": false,
      "supported": false
    },
    "DomRange": {
      "name": "DomRange",
      "dependencies": [
        "DomUtil"
      ],
      "initialized": false,
      "supported": false
    },
    "WrappedRange": {
      "name": "WrappedRange",
      "dependencies": [
        "DomRange"
      ],
      "initialized": false,
      "supported": false
    },
    "WrappedSelection": {
      "name": "WrappedSelection",
      "dependencies": [
        "DomRange",
        "WrappedRange"
      ],
      "initialized": false,
      "supported": false
    }
  },
  "config": {
    "alertOnFail": true,
    "alertOnWarn": false,
    "preferTextRange": false,
    "autoInitialize": true
  },
  "rangePrototype": {},
  "selectionPrototype": {}
}
```
If you have examples for rjs, please share.

**Comment by oscarotero** [comment]
In my requirejs context, I'm using the 0.4.12 version because from 0.4.13 the library cannot be loaded due the `rangy is not defined` error.

**Comment by pulges** [comment]
The new version 0.6.0-beta has removed the bundled rangy UMD wrappers now. Any other blocking problems when bundling or can the issue be closed?
